import type { Metadata } from "next";
import { Roboto } from "next/font/google"
import { Header } from "./components/shared/Header";
import { Footer } from "./components/shared/Footer";
import "./globals.css";

export const metadata: Metadata = {
  title: "Happy Sticker",
  description: "Generated by create next app",
};

const roboto = Roboto({
  weight: ["100", "300", "500", "700"],
  subsets: ["latin"]
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        {/* <Header/> */}
        {children}
        <Footer/>
      </body>
    </html>
  );
}
